"""Create committees table

Revision ID: 0a99e4fe4e2c
Revises: 79bc0fd8ed87
Create Date: 2025-10-25 12:49:40.363941

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a99e4fe4e2c"
down_revision: Union[str, Sequence[str], None] = "79bc0fd8ed87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "committees",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fec_committee_id", sa.String(length=9), nullable=False),
        sa.Column("committee_name", sa.String(length=200), nullable=False),
        sa.Column("committee_type", sa.String(length=1), nullable=True),
        sa.Column("designation", sa.String(length=1), nullable=True),
        sa.Column("party_affiliation", sa.String(length=3), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_committees_fec_committee_id"),
        "committees",
        ["fec_committee_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_committees_fec_committee_id"), table_name="committees")
    op.drop_table("committees")
    # ### end Alembic commands ###
