"""Make entity_type nullable in silver and gold

Revision ID: 0f708bc57915
Revises: e75e2c3e4927
Create Date: 2025-11-22 13:58:15.483039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f708bc57915'
down_revision: Union[str, Sequence[str], None] = 'e75e2c3e4927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gold_contributor', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('silver_fec_contribution', 'entity_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_fec_contribution', 'entity_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('gold_contributor', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
