"""Create contributions table

Revision ID: 14a5a00448d1
Revises: aaa112bb248c
Create Date: 2025-10-25 13:19:34.555604

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14a5a00448d1"
down_revision: Union[str, Sequence[str], None] = "aaa112bb248c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contributions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_table", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("contribution_date", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("donor_name_raw", sa.String(length=200), nullable=False),
        sa.Column("donor_employer_raw", sa.String(length=200), nullable=True),
        sa.Column("donor_occupation_raw", sa.String(length=100), nullable=True),
        sa.Column("donor_city", sa.String(length=50), nullable=True),
        sa.Column("donor_state", sa.String(length=2), nullable=True),
        sa.Column("donor_zip", sa.String(length=9), nullable=True),
        sa.Column("donor_id", sa.BigInteger(), nullable=True),
        sa.Column("recipient_committee_id", sa.BigInteger(), nullable=False),
        sa.Column("recipient_candidate_id", sa.BigInteger(), nullable=True),
        sa.Column("contribution_type", sa.String(length=20), nullable=False),
        sa.Column("transaction_type", sa.String(length=3), nullable=True),
        sa.Column("election_type", sa.String(length=20), nullable=True),
        sa.Column("is_itemized", sa.Boolean(), nullable=False),
        sa.Column("memo_text", sa.Text(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["donors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_candidate_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_committee_id"],
            ["committees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_table", "source_id", name="uq_contribution_source"),
    )
    op.create_index(
        op.f("ix_contributions_amount_cents"),
        "contributions",
        ["amount_cents"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_contribution_date"),
        "contributions",
        ["contribution_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_donor_employer_raw"),
        "contributions",
        ["donor_employer_raw"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_donor_id"), "contributions", ["donor_id"], unique=False
    )
    op.create_index(
        op.f("ix_contributions_donor_name_raw"),
        "contributions",
        ["donor_name_raw"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_needs_review"),
        "contributions",
        ["needs_review"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_recipient_candidate_id"),
        "contributions",
        ["recipient_candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_recipient_committee_id"),
        "contributions",
        ["recipient_committee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_contributions_recipient_committee_id"), table_name="contributions"
    )
    op.drop_index(
        op.f("ix_contributions_recipient_candidate_id"), table_name="contributions"
    )
    op.drop_index(op.f("ix_contributions_needs_review"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_donor_name_raw"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_donor_id"), table_name="contributions")
    op.drop_index(
        op.f("ix_contributions_donor_employer_raw"), table_name="contributions"
    )
    op.drop_index(
        op.f("ix_contributions_contribution_date"), table_name="contributions"
    )
    op.drop_index(op.f("ix_contributions_amount_cents"), table_name="contributions")
    op.drop_table("contributions")
    # ### end Alembic commands ###
