"""add_maryland_bronze_tables

Revision ID: 22201b46ddde
Revises: c9b4e7f12d38
Create Date: 2025-11-29 19:24:08.530344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22201b46ddde'
down_revision: Union[str, Sequence[str], None] = 'c9b4e7f12d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_md_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('office_name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('candidate_last_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_first_name', sa.String(length=255), nullable=False),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('filing_type_and_date', sa.String(length=255), nullable=True),
    sa.Column('campaign_address', sa.String(length=500), nullable=True),
    sa.Column('campaign_city_state_zip', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('facebook', sa.String(length=500), nullable=True),
    sa.Column('twitter', sa.String(length=500), nullable=True),
    sa.Column('other_social', sa.String(length=500), nullable=True),
    sa.Column('committee_name', sa.String(length=255), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_md_candidate_committee_name'), 'bronze_md_candidate', ['committee_name'], unique=False)
    op.create_index(op.f('ix_bronze_md_candidate_content_hash'), 'bronze_md_candidate', ['content_hash'], unique=True)
    op.create_index(op.f('ix_bronze_md_candidate_election_type'), 'bronze_md_candidate', ['election_type'], unique=False)
    op.create_index(op.f('ix_bronze_md_candidate_election_year'), 'bronze_md_candidate', ['election_year'], unique=False)
    op.create_index(op.f('ix_bronze_md_candidate_office_name'), 'bronze_md_candidate', ['office_name'], unique=False)
    op.create_index(op.f('ix_bronze_md_candidate_party'), 'bronze_md_candidate', ['party'], unique=False)
    op.create_index(op.f('ix_bronze_md_candidate_source_system'), 'bronze_md_candidate', ['source_system'], unique=False)
    op.create_index(op.f('ix_bronze_md_candidate_status'), 'bronze_md_candidate', ['status'], unique=False)
    op.create_table('bronze_md_committee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ccf_id', sa.String(length=20), nullable=False),
    sa.Column('committee_type', sa.String(length=100), nullable=False),
    sa.Column('committee_name', sa.String(length=255), nullable=False),
    sa.Column('committee_status', sa.String(length=50), nullable=False),
    sa.Column('citation_violations', sa.Text(), nullable=True),
    sa.Column('election_type', sa.String(length=255), nullable=True),
    sa.Column('registered_date', sa.String(length=20), nullable=False),
    sa.Column('amended_date', sa.String(length=20), nullable=True),
    sa.Column('chairperson_name', sa.String(length=255), nullable=True),
    sa.Column('chairperson_address', sa.String(length=500), nullable=True),
    sa.Column('treasurer_name', sa.String(length=255), nullable=True),
    sa.Column('treasurer_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_md_committee_ccf_id'), 'bronze_md_committee', ['ccf_id'], unique=True)
    op.create_index(op.f('ix_bronze_md_committee_committee_name'), 'bronze_md_committee', ['committee_name'], unique=False)
    op.create_index(op.f('ix_bronze_md_committee_source_system'), 'bronze_md_committee', ['source_system'], unique=False)
    op.create_table('bronze_md_contribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('receiving_committee', sa.String(length=255), nullable=False),
    sa.Column('filing_period', sa.String(length=100), nullable=False),
    sa.Column('contribution_date', sa.String(length=20), nullable=False),
    sa.Column('contributor_name', sa.String(length=255), nullable=False),
    sa.Column('contributor_address', sa.String(length=500), nullable=False),
    sa.Column('contributor_type', sa.String(length=100), nullable=False),
    sa.Column('contribution_type', sa.String(length=100), nullable=False),
    sa.Column('contribution_amount', sa.String(length=50), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('employer_occupation', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('fund_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_md_contribution_content_hash'), 'bronze_md_contribution', ['content_hash'], unique=True)
    op.create_index(op.f('ix_bronze_md_contribution_receiving_committee'), 'bronze_md_contribution', ['receiving_committee'], unique=False)
    op.create_index(op.f('ix_bronze_md_contribution_source_system'), 'bronze_md_contribution', ['source_system'], unique=False)
    op.create_table('bronze_md_extraction_state',
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('filing_year', sa.Integer(), nullable=False),
    sa.Column('last_extraction_date', sa.Date(), nullable=False),
    sa.Column('last_extraction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_records_extracted', sa.Integer(), nullable=False),
    sa.Column('extraction_start_date', sa.Date(), nullable=True),
    sa.Column('extraction_end_date', sa.Date(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('data_type', 'filing_year')
    )
    op.create_index(op.f('ix_bronze_md_extraction_state_last_extraction_date'), 'bronze_md_extraction_state', ['last_extraction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bronze_md_extraction_state_last_extraction_date'), table_name='bronze_md_extraction_state')
    op.drop_table('bronze_md_extraction_state')
    op.drop_index(op.f('ix_bronze_md_contribution_source_system'), table_name='bronze_md_contribution')
    op.drop_index(op.f('ix_bronze_md_contribution_receiving_committee'), table_name='bronze_md_contribution')
    op.drop_index(op.f('ix_bronze_md_contribution_content_hash'), table_name='bronze_md_contribution')
    op.drop_table('bronze_md_contribution')
    op.drop_index(op.f('ix_bronze_md_committee_source_system'), table_name='bronze_md_committee')
    op.drop_index(op.f('ix_bronze_md_committee_committee_name'), table_name='bronze_md_committee')
    op.drop_index(op.f('ix_bronze_md_committee_ccf_id'), table_name='bronze_md_committee')
    op.drop_table('bronze_md_committee')
    op.drop_index(op.f('ix_bronze_md_candidate_status'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_source_system'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_party'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_office_name'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_election_year'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_election_type'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_content_hash'), table_name='bronze_md_candidate')
    op.drop_index(op.f('ix_bronze_md_candidate_committee_name'), table_name='bronze_md_candidate')
    op.drop_table('bronze_md_candidate')
    # ### end Alembic commands ###
