"""Remove unique constraint from raw_filings file_hash

Revision ID: 46b1ad3bf030
Revises: cd3759026388
Create Date: 2025-10-25 14:30:46.839438

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46b1ad3bf030"
down_revision: Union[str, Sequence[str], None] = "cd3759026388"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("raw_filings_file_hash_key"), "raw_filings", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("raw_filings_file_hash_key"),
        "raw_filings",
        ["file_hash"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
