"""Create fec_contributions_staging table

Revision ID: 5cb2f0eb777c
Revises: de61cbeea719
Create Date: 2025-10-25 13:09:29.202134

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cb2f0eb777c"
down_revision: Union[str, Sequence[str], None] = "de61cbeea719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fec_contributions_staging",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("raw_filing_id", sa.BigInteger(), nullable=False),
        sa.Column("cmte_id", sa.String(length=9), nullable=True),
        sa.Column("amndt_ind", sa.String(length=1), nullable=True),
        sa.Column("rpt_tp", sa.String(length=3), nullable=True),
        sa.Column("transaction_pgi", sa.String(length=5), nullable=True),
        sa.Column("image_num", sa.String(length=18), nullable=True),
        sa.Column("transaction_tp", sa.String(length=3), nullable=True),
        sa.Column("entity_tp", sa.String(length=3), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=30), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=9), nullable=True),
        sa.Column("employer", sa.Text(), nullable=True),
        sa.Column("occupation", sa.Text(), nullable=True),
        sa.Column("transaction_dt", sa.String(length=8), nullable=True),
        sa.Column("transaction_amt", sa.String(length=14), nullable=True),
        sa.Column("other_id", sa.String(length=9), nullable=True),
        sa.Column("tran_id", sa.String(length=32), nullable=True),
        sa.Column("file_num", sa.String(length=22), nullable=True),
        sa.Column("memo_cd", sa.String(length=1), nullable=True),
        sa.Column("memo_text", sa.Text(), nullable=True),
        sa.Column("sub_id", sa.String(length=19), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("standardized", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_filing_id"],
            ["raw_filings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fec_contributions_staging_raw_filing_id"),
        "fec_contributions_staging",
        ["raw_filing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fec_contributions_staging_standardized"),
        "fec_contributions_staging",
        ["standardized"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fec_contributions_staging_standardized"),
        table_name="fec_contributions_staging",
    )
    op.drop_index(
        op.f("ix_fec_contributions_staging_raw_filing_id"),
        table_name="fec_contributions_staging",
    )
    op.drop_table("fec_contributions_staging")
    # ### end Alembic commands ###
