"""Create candidates table

Revision ID: 6511fadb3b71
Revises: 0a99e4fe4e2c
Create Date: 2025-10-25 12:54:04.361045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6511fadb3b71'
down_revision: Union[str, Sequence[str], None] = '0a99e4fe4e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fec_candidate_id', sa.String(length=9), nullable=False),
    sa.Column('candidate_name', sa.String(length=200), nullable=False),
    sa.Column('party', sa.String(length=3), nullable=True),
    sa.Column('office', sa.String(length=1), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.String(length=2), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_committee_id'), 'candidates', ['committee_id'], unique=False)
    op.create_index(op.f('ix_candidates_fec_candidate_id'), 'candidates', ['fec_candidate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_fec_candidate_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_committee_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
