"""Add enriched fields to silver and party to gold committee

Revision ID: 7e2afd0dcba6
Revises: b67f9f8896a8
Create Date: 2025-10-30 14:36:30.175179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2afd0dcba6'
down_revision: Union[str, Sequence[str], None] = 'b67f9f8896a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold_committee', sa.Column('party', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_gold_committee_party'), 'gold_committee', ['party'], unique=False)
    op.add_column('silver_fec_contribution', sa.Column('committee_party', sa.String(length=10), nullable=True))
    op.add_column('silver_fec_contribution', sa.Column('candidate_id', sa.String(length=20), nullable=True))
    op.add_column('silver_fec_contribution', sa.Column('candidate_name', sa.String(length=500), nullable=True))
    op.add_column('silver_fec_contribution', sa.Column('candidate_office', sa.String(length=1), nullable=True))
    op.add_column('silver_fec_contribution', sa.Column('candidate_party', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_silver_fec_contribution_candidate_id'), 'silver_fec_contribution', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_fec_contribution_candidate_id'), table_name='silver_fec_contribution')
    op.drop_column('silver_fec_contribution', 'candidate_party')
    op.drop_column('silver_fec_contribution', 'candidate_office')
    op.drop_column('silver_fec_contribution', 'candidate_name')
    op.drop_column('silver_fec_contribution', 'candidate_id')
    op.drop_column('silver_fec_contribution', 'committee_party')
    op.drop_index(op.f('ix_gold_committee_party'), table_name='gold_committee')
    op.drop_column('gold_committee', 'party')
    # ### end Alembic commands ###
