"""make_bronze_md_contribution_contributor_fields_nullable

Revision ID: 9e49ab3b53c6
Revises: d4dff7c0ddef
Create Date: 2025-12-01 12:45:46.332005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e49ab3b53c6'
down_revision: Union[str, Sequence[str], None] = 'd4dff7c0ddef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bronze_md_contribution', 'contributor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bronze_md_contribution', 'contributor_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('bronze_md_contribution', 'contributor_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bronze_md_contribution', 'contributor_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bronze_md_contribution', 'contributor_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('bronze_md_contribution', 'contributor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
