"""Create donors table

Revision ID: aaa112bb248c
Revises: 5cb2f0eb777c
Create Date: 2025-10-25 13:14:52.701966

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaa112bb248c"
down_revision: Union[str, Sequence[str], None] = "5cb2f0eb777c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("employer_canonical", sa.String(length=200), nullable=True),
        sa.Column("occupation_canonical", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip", sa.String(length=9), nullable=True),
        sa.Column("entity_resolution_confidence", sa.Float(), nullable=True),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_donors_canonical_name"), "donors", ["canonical_name"], unique=False
    )
    op.create_index(
        op.f("ix_donors_employer_canonical"),
        "donors",
        ["employer_canonical"],
        unique=False,
    )
    op.create_index(op.f("ix_donors_state"), "donors", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_donors_state"), table_name="donors")
    op.drop_index(op.f("ix_donors_employer_canonical"), table_name="donors")
    op.drop_index(op.f("ix_donors_canonical_name"), table_name="donors")
    op.drop_table("donors")
    # ### end Alembic commands ###
