"""Add missing fields to bronze committee and candidate models

Revision ID: b67f9f8896a8
Revises: f04ae2a6a9e1
Create Date: 2025-10-30 13:42:11.216195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67f9f8896a8'
down_revision: Union[str, Sequence[str], None] = 'f04ae2a6a9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bronze_fec_candidate', sa.Column('candidate_first_name', sa.String(length=255), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('candidate_last_name', sa.String(length=255), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('candidate_middle_name', sa.String(length=255), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('district_number', sa.Integer(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('incumbent_challenge', sa.String(length=1), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('incumbent_challenge_full', sa.String(length=100), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('election_districts', sa.JSON(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('candidate_inactive', sa.Boolean(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('first_file_date', sa.Date(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('last_file_date', sa.Date(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('last_f2_date', sa.Date(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('has_raised_funds', sa.Boolean(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('federal_funds_flag', sa.Boolean(), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('address_city', sa.String(length=255), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('address_state', sa.String(length=2), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('address_street_1', sa.String(length=500), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('address_street_2', sa.String(length=500), nullable=True))
    op.add_column('bronze_fec_candidate', sa.Column('address_zip', sa.String(length=10), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('party', sa.String(length=10), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('party_full', sa.String(length=100), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('organization_type', sa.String(length=1), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('organization_type_full', sa.String(length=100), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('filing_frequency', sa.String(length=1), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('first_file_date', sa.Date(), nullable=True))
    op.add_column('bronze_fec_committee', sa.Column('last_file_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bronze_fec_committee', 'last_file_date')
    op.drop_column('bronze_fec_committee', 'first_file_date')
    op.drop_column('bronze_fec_committee', 'filing_frequency')
    op.drop_column('bronze_fec_committee', 'organization_type_full')
    op.drop_column('bronze_fec_committee', 'organization_type')
    op.drop_column('bronze_fec_committee', 'party_full')
    op.drop_column('bronze_fec_committee', 'party')
    op.drop_column('bronze_fec_candidate', 'address_zip')
    op.drop_column('bronze_fec_candidate', 'address_street_2')
    op.drop_column('bronze_fec_candidate', 'address_street_1')
    op.drop_column('bronze_fec_candidate', 'address_state')
    op.drop_column('bronze_fec_candidate', 'address_city')
    op.drop_column('bronze_fec_candidate', 'federal_funds_flag')
    op.drop_column('bronze_fec_candidate', 'has_raised_funds')
    op.drop_column('bronze_fec_candidate', 'last_f2_date')
    op.drop_column('bronze_fec_candidate', 'last_file_date')
    op.drop_column('bronze_fec_candidate', 'first_file_date')
    op.drop_column('bronze_fec_candidate', 'candidate_inactive')
    op.drop_column('bronze_fec_candidate', 'election_districts')
    op.drop_column('bronze_fec_candidate', 'incumbent_challenge_full')
    op.drop_column('bronze_fec_candidate', 'incumbent_challenge')
    op.drop_column('bronze_fec_candidate', 'district_number')
    op.drop_column('bronze_fec_candidate', 'candidate_middle_name')
    op.drop_column('bronze_fec_candidate', 'candidate_last_name')
    op.drop_column('bronze_fec_candidate', 'candidate_first_name')
    # ### end Alembic commands ###
