"""Make committee name nullable

Revision ID: b7a86bbb7137
Revises: 0f708bc57915
Create Date: 2025-11-22 17:47:59.789951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a86bbb7137'
down_revision: Union[str, Sequence[str], None] = '0f708bc57915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gold_committee', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('silver_fec_committee', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_fec_committee', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('gold_committee', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
