"""add_extraction_metadata_table

Revision ID: ba224162ca90
Revises: a707f904e4bb
Create Date: 2025-10-26 17:20:23.229980

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba224162ca90"
down_revision: Union[str, Sequence[str], None] = "a707f904e4bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="Source system (e.g., fec_api)",
        ),
        sa.Column(
            "entity_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of entity (e.g., contributions)",
        ),
        sa.Column(
            "state",
            sa.String(length=2),
            nullable=False,
            comment="State code (e.g., MD)",
        ),
        sa.Column(
            "cycle",
            sa.Integer(),
            nullable=False,
            comment="Two-year transaction period (e.g., 2026)",
        ),
        sa.Column(
            "last_processed_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Latest contribution date processed",
        ),
        sa.Column(
            "last_extraction_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this extraction run completed",
        ),
        sa.Column(
            "records_extracted",
            sa.Integer(),
            nullable=False,
            comment="Number of records extracted in last run",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="active, paused, completed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "entity_type", "state", "cycle", name="uq_extraction_metadata_key"
        ),
    )
    op.create_index(
        "ix_extraction_metadata_lookup",
        "extraction_metadata",
        ["source", "entity_type", "state", "cycle", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_extraction_metadata_lookup", table_name="extraction_metadata")
    op.drop_table("extraction_metadata")
    # ### end Alembic commands ###
