"""add_maryland_silver_tables

Revision ID: c60de9a45492
Revises: 22201b46ddde
Create Date: 2025-12-01 11:02:39.038644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60de9a45492'
down_revision: Union[str, Sequence[str], None] = '22201b46ddde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silver_md_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_content_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('committee_name', sa.String(length=255), nullable=True),
    sa.Column('committee_ccf_id', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_md_candidate_committee_ccf_id'), 'silver_md_candidate', ['committee_ccf_id'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_committee_name'), 'silver_md_candidate', ['committee_name'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_election_type'), 'silver_md_candidate', ['election_type'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_election_year'), 'silver_md_candidate', ['election_year'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_name'), 'silver_md_candidate', ['name'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_office'), 'silver_md_candidate', ['office'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_party'), 'silver_md_candidate', ['party'], unique=False)
    op.create_index(op.f('ix_silver_md_candidate_source_content_hash'), 'silver_md_candidate', ['source_content_hash'], unique=True)
    op.create_table('silver_md_committee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ccf_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('committee_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('election_type', sa.String(length=255), nullable=True),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('amended_date', sa.Date(), nullable=True),
    sa.Column('chairperson_name', sa.String(length=255), nullable=True),
    sa.Column('treasurer_name', sa.String(length=255), nullable=True),
    sa.Column('has_violations', sa.Boolean(), nullable=False),
    sa.Column('citation_violations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_md_committee_name'), 'silver_md_committee', ['name'], unique=False)
    op.create_index(op.f('ix_silver_md_committee_source_ccf_id'), 'silver_md_committee', ['source_ccf_id'], unique=True)
    op.create_table('silver_md_contribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_content_hash', sa.String(length=64), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_type', sa.String(length=100), nullable=False),
    sa.Column('fund_type', sa.String(length=100), nullable=True),
    sa.Column('contributor_name', sa.String(length=255), nullable=False),
    sa.Column('contributor_type', sa.String(length=100), nullable=False),
    sa.Column('contributor_address', sa.String(length=500), nullable=True),
    sa.Column('contributor_city', sa.String(length=255), nullable=True),
    sa.Column('contributor_state', sa.String(length=2), nullable=True),
    sa.Column('contributor_zip', sa.String(length=10), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('employer_occupation', sa.String(length=255), nullable=True),
    sa.Column('committee_name', sa.String(length=255), nullable=False),
    sa.Column('committee_ccf_id', sa.String(length=20), nullable=True),
    sa.Column('committee_type', sa.String(length=100), nullable=True),
    sa.Column('filing_period', sa.String(length=100), nullable=False),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_md_contribution_committee_ccf_id'), 'silver_md_contribution', ['committee_ccf_id'], unique=False)
    op.create_index(op.f('ix_silver_md_contribution_committee_name'), 'silver_md_contribution', ['committee_name'], unique=False)
    op.create_index(op.f('ix_silver_md_contribution_contribution_date'), 'silver_md_contribution', ['contribution_date'], unique=False)
    op.create_index(op.f('ix_silver_md_contribution_contributor_city'), 'silver_md_contribution', ['contributor_city'], unique=False)
    op.create_index(op.f('ix_silver_md_contribution_contributor_name'), 'silver_md_contribution', ['contributor_name'], unique=False)
    op.create_index(op.f('ix_silver_md_contribution_contributor_state'), 'silver_md_contribution', ['contributor_state'], unique=False)
    op.create_index(op.f('ix_silver_md_contribution_source_content_hash'), 'silver_md_contribution', ['source_content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_md_contribution_source_content_hash'), table_name='silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_contribution_contributor_state'), table_name='silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_contribution_contributor_name'), table_name='silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_contribution_contributor_city'), table_name='silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_contribution_contribution_date'), table_name='silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_contribution_committee_name'), table_name='silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_contribution_committee_ccf_id'), table_name='silver_md_contribution')
    op.drop_table('silver_md_contribution')
    op.drop_index(op.f('ix_silver_md_committee_source_ccf_id'), table_name='silver_md_committee')
    op.drop_index(op.f('ix_silver_md_committee_name'), table_name='silver_md_committee')
    op.drop_table('silver_md_committee')
    op.drop_index(op.f('ix_silver_md_candidate_source_content_hash'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_party'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_office'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_name'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_election_year'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_election_type'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_committee_name'), table_name='silver_md_candidate')
    op.drop_index(op.f('ix_silver_md_candidate_committee_ccf_id'), table_name='silver_md_candidate')
    op.drop_table('silver_md_candidate')
    # ### end Alembic commands ###
