"""Create contribution_aggregates table

Revision ID: cd3759026388
Revises: 14a5a00448d1
Create Date: 2025-10-25 13:24:46.593609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3759026388'
down_revision: Union[str, Sequence[str], None] = '14a5a00448d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_aggregates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('aggregation_period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_raised_cents', sa.Integer(), nullable=False),
    sa.Column('total_spent_cents', sa.Integer(), nullable=False),
    sa.Column('total_cash_on_hand_cents', sa.Integer(), nullable=False),
    sa.Column('total_debts_cents', sa.Integer(), nullable=False),
    sa.Column('individual_contributions_count', sa.Integer(), nullable=False),
    sa.Column('individual_contributions_cents', sa.Integer(), nullable=False),
    sa.Column('pac_contributions_count', sa.Integer(), nullable=False),
    sa.Column('pac_contributions_cents', sa.Integer(), nullable=False),
    sa.Column('party_contributions_count', sa.Integer(), nullable=False),
    sa.Column('party_contributions_cents', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'aggregation_period', 'period_start', name='uq_aggregate_period')
    )
    op.create_index(op.f('ix_contribution_aggregates_candidate_id'), 'contribution_aggregates', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_aggregates_candidate_id'), table_name='contribution_aggregates')
    op.drop_table('contribution_aggregates')
    # ### end Alembic commands ###
