"""Add party and candidate_id to silver_fec_committee

Revision ID: d529a28e33e0
Revises: 7e2afd0dcba6
Create Date: 2025-11-03 11:55:13.835054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd529a28e33e0'
down_revision: Union[str, Sequence[str], None] = '7e2afd0dcba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_fec_committee', sa.Column('party', sa.String(length=10), nullable=True))
    op.add_column('silver_fec_committee', sa.Column('candidate_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_silver_fec_committee_candidate_id'), 'silver_fec_committee', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_fec_committee_candidate_id'), table_name='silver_fec_committee')
    op.drop_column('silver_fec_committee', 'candidate_id')
    op.drop_column('silver_fec_committee', 'party')
    # ### end Alembic commands ###
