"""Add candidate_id and metadata fields to bronze_fec_schedule_a

Revision ID: d80bab2f7ba1
Revises: b7a86bbb7137
Create Date: 2025-11-23 14:09:04.194153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80bab2f7ba1'
down_revision: Union[str, Sequence[str], None] = 'b7a86bbb7137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bronze_fec_schedule_a', sa.Column('candidate_id', sa.String(length=20), nullable=True))
    op.add_column('bronze_fec_schedule_a', sa.Column('image_number', sa.String(length=20), nullable=True))
    op.add_column('bronze_fec_schedule_a', sa.Column('other_id', sa.String(length=20), nullable=True))
    op.add_column('bronze_fec_schedule_a', sa.Column('is_individual', sa.Boolean(), nullable=True))
    op.add_column('bronze_fec_schedule_a', sa.Column('line_number', sa.String(length=10), nullable=True))
    op.add_column('bronze_fec_schedule_a', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    op.add_column('bronze_fec_schedule_a', sa.Column('original_sub_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_bronze_fec_schedule_a_candidate_id'), 'bronze_fec_schedule_a', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bronze_fec_schedule_a_candidate_id'), table_name='bronze_fec_schedule_a')
    op.drop_column('bronze_fec_schedule_a', 'original_sub_id')
    op.drop_column('bronze_fec_schedule_a', 'pdf_url')
    op.drop_column('bronze_fec_schedule_a', 'line_number')
    op.drop_column('bronze_fec_schedule_a', 'is_individual')
    op.drop_column('bronze_fec_schedule_a', 'other_id')
    op.drop_column('bronze_fec_schedule_a', 'image_number')
    op.drop_column('bronze_fec_schedule_a', 'candidate_id')
    # ### end Alembic commands ###
