"""Add source tracking to committees and candidates

Revision ID: de61cbeea719
Revises: 6511fadb3b71
Create Date: 2025-10-25 13:04:13.514015

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de61cbeea719"
down_revision: Union[str, Sequence[str], None] = "6511fadb3b71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidates", sa.Column("data_source", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "candidates",
        sa.Column("source_candidate_id", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "candidates", sa.Column("office_level", sa.String(length=20), nullable=False)
    )
    op.alter_column(
        "candidates",
        "fec_candidate_id",
        existing_type=sa.VARCHAR(length=9),
        nullable=True,
    )
    op.drop_index(op.f("ix_candidates_fec_candidate_id"), table_name="candidates")
    op.create_index(
        op.f("ix_candidates_fec_candidate_id"),
        "candidates",
        ["fec_candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidates_data_source"), "candidates", ["data_source"], unique=False
    )
    op.create_unique_constraint(
        "uq_candidate_source_id", "candidates", ["data_source", "source_candidate_id"]
    )
    op.add_column(
        "committees", sa.Column("data_source", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "committees",
        sa.Column("source_committee_id", sa.String(length=50), nullable=False),
    )
    op.alter_column(
        "committees",
        "fec_committee_id",
        existing_type=sa.VARCHAR(length=9),
        nullable=True,
    )
    op.drop_index(op.f("ix_committees_fec_committee_id"), table_name="committees")
    op.create_index(
        op.f("ix_committees_fec_committee_id"),
        "committees",
        ["fec_committee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committees_data_source"), "committees", ["data_source"], unique=False
    )
    op.create_unique_constraint(
        "uq_committee_source_id", "committees", ["data_source", "source_committee_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_committee_source_id", "committees", type_="unique")
    op.drop_index(op.f("ix_committees_data_source"), table_name="committees")
    op.drop_index(op.f("ix_committees_fec_committee_id"), table_name="committees")
    op.create_index(
        op.f("ix_committees_fec_committee_id"),
        "committees",
        ["fec_committee_id"],
        unique=True,
    )
    op.alter_column(
        "committees",
        "fec_committee_id",
        existing_type=sa.VARCHAR(length=9),
        nullable=False,
    )
    op.drop_column("committees", "source_committee_id")
    op.drop_column("committees", "data_source")
    op.drop_constraint("uq_candidate_source_id", "candidates", type_="unique")
    op.drop_index(op.f("ix_candidates_data_source"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_fec_candidate_id"), table_name="candidates")
    op.create_index(
        op.f("ix_candidates_fec_candidate_id"),
        "candidates",
        ["fec_candidate_id"],
        unique=True,
    )
    op.alter_column(
        "candidates",
        "fec_candidate_id",
        existing_type=sa.VARCHAR(length=9),
        nullable=False,
    )
    op.drop_column("candidates", "office_level")
    op.drop_column("candidates", "source_candidate_id")
    op.drop_column("candidates", "data_source")
    # ### end Alembic commands ###
