"""Make transaction_id nullable in silver and gold

Revision ID: e75e2c3e4927
Revises: fd68e26103e4
Create Date: 2025-11-22 13:10:40.134186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75e2c3e4927'
down_revision: Union[str, Sequence[str], None] = 'fd68e26103e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gold_contribution', 'source_transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('uq_source_sub_id'), 'gold_contribution', type_='unique')
    op.create_unique_constraint('uq_source_transaction', 'gold_contribution', ['source_system', 'source_sub_id'])
    op.alter_column('silver_fec_contribution', 'transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_fec_contribution', 'transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('uq_source_transaction', 'gold_contribution', type_='unique')
    op.create_unique_constraint(op.f('uq_source_sub_id'), 'gold_contribution', ['source_system', 'source_sub_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('gold_contribution', 'source_transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
