"""expand_gold_candidate_district_length

Revision ID: ed277a7c8a51
Revises: c60de9a45492
Create Date: 2025-12-01 11:34:46.208011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed277a7c8a51'
down_revision: Union[str, Sequence[str], None] = 'c60de9a45492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gold_candidate', 'district',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gold_contribution_candidate_stats'), 'gold_contribution', ['recipient_candidate_id', 'amount'], unique=False, postgresql_where='(recipient_candidate_id IS NOT NULL)')
    op.alter_column('gold_candidate', 'district',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
