"""Initial migration: bronze, silver, gold tables

Revision ID: f04ae2a6a9e1
Revises:
Create Date: 2025-10-29 17:05:56.399840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04ae2a6a9e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_fec_candidate',
    sa.Column('candidate_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('office', sa.String(length=1), nullable=True),
    sa.Column('office_full', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('district', sa.String(length=2), nullable=True),
    sa.Column('party', sa.String(length=10), nullable=True),
    sa.Column('party_full', sa.String(length=100), nullable=True),
    sa.Column('cycles', sa.JSON(), nullable=True),
    sa.Column('election_years', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('candidate_status', sa.String(length=1), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_bronze_fec_candidate_source_system'), 'bronze_fec_candidate', ['source_system'], unique=False)
    op.create_index(op.f('ix_bronze_fec_candidate_state'), 'bronze_fec_candidate', ['state'], unique=False)
    op.create_table('bronze_fec_committee',
    sa.Column('committee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('committee_type', sa.String(length=1), nullable=True),
    sa.Column('committee_type_full', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=1), nullable=True),
    sa.Column('designation_full', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('street_1', sa.String(length=500), nullable=True),
    sa.Column('street_2', sa.String(length=500), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('treasurer_name', sa.String(length=500), nullable=True),
    sa.Column('candidate_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cycles', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('committee_id')
    )
    op.create_index(op.f('ix_bronze_fec_committee_source_system'), 'bronze_fec_committee', ['source_system'], unique=False)
    op.create_index(op.f('ix_bronze_fec_committee_state'), 'bronze_fec_committee', ['state'], unique=False)
    op.create_table('bronze_fec_extraction_state',
    sa.Column('committee_id', sa.String(length=20), nullable=False),
    sa.Column('election_cycle', sa.Integer(), nullable=False),
    sa.Column('last_contribution_date', sa.Date(), nullable=False),
    sa.Column('last_sub_id', sa.String(length=255), nullable=False),
    sa.Column('total_contributions_extracted', sa.Integer(), nullable=False),
    sa.Column('last_extraction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extraction_start_date', sa.Date(), nullable=True),
    sa.Column('extraction_end_date', sa.Date(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('last_page_processed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('committee_id', 'election_cycle')
    )
    op.create_index(op.f('ix_bronze_fec_extraction_state_last_contribution_date'), 'bronze_fec_extraction_state', ['last_contribution_date'], unique=False)
    op.create_table('bronze_fec_schedule_a',
    sa.Column('sub_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('file_number', sa.Integer(), nullable=True),
    sa.Column('amendment_indicator', sa.String(length=10), nullable=True),
    sa.Column('contribution_receipt_date', sa.Date(), nullable=True),
    sa.Column('contribution_receipt_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contributor_aggregate_ytd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contributor_name', sa.String(length=500), nullable=True),
    sa.Column('contributor_first_name', sa.String(length=255), nullable=True),
    sa.Column('contributor_last_name', sa.String(length=255), nullable=True),
    sa.Column('contributor_middle_name', sa.String(length=255), nullable=True),
    sa.Column('contributor_city', sa.String(length=255), nullable=True),
    sa.Column('contributor_state', sa.String(length=2), nullable=True),
    sa.Column('contributor_zip', sa.String(length=10), nullable=True),
    sa.Column('contributor_employer', sa.String(length=500), nullable=True),
    sa.Column('contributor_occupation', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=10), nullable=True),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('recipient_committee_designation', sa.String(length=10), nullable=True),
    sa.Column('recipient_committee_type', sa.String(length=10), nullable=True),
    sa.Column('recipient_committee_org_type', sa.String(length=10), nullable=True),
    sa.Column('receipt_type', sa.String(length=10), nullable=True),
    sa.Column('election_type', sa.String(length=10), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('memo_code', sa.String(length=10), nullable=True),
    sa.Column('two_year_transaction_period', sa.Integer(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=10), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index(op.f('ix_bronze_fec_schedule_a_committee_id'), 'bronze_fec_schedule_a', ['committee_id'], unique=False)
    op.create_index(op.f('ix_bronze_fec_schedule_a_source_system'), 'bronze_fec_schedule_a', ['source_system'], unique=False)
    op.create_table('gold_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('office', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fec_candidate_id', sa.String(length=20), nullable=True),
    sa.Column('state_candidate_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_candidate_id')
    )
    op.create_index(op.f('ix_gold_candidate_name'), 'gold_candidate', ['name'], unique=False)
    op.create_index(op.f('ix_gold_candidate_office'), 'gold_candidate', ['office'], unique=False)
    op.create_index(op.f('ix_gold_candidate_party'), 'gold_candidate', ['party'], unique=False)
    op.create_index(op.f('ix_gold_candidate_state'), 'gold_candidate', ['state'], unique=False)
    op.create_table('gold_committee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('committee_type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('fec_committee_id', sa.String(length=20), nullable=True),
    sa.Column('state_committee_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_committee_id')
    )
    op.create_index(op.f('ix_gold_committee_candidate_id'), 'gold_committee', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_gold_committee_committee_type'), 'gold_committee', ['committee_type'], unique=False)
    op.create_index(op.f('ix_gold_committee_name'), 'gold_committee', ['name'], unique=False)
    op.create_index(op.f('ix_gold_committee_state'), 'gold_committee', ['state'], unique=False)
    op.create_table('gold_contribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('recipient_committee_id', sa.Integer(), nullable=False),
    sa.Column('recipient_candidate_id', sa.Integer(), nullable=True),
    sa.Column('contribution_type', sa.String(length=50), nullable=False),
    sa.Column('election_type', sa.String(length=20), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('election_cycle', sa.Integer(), nullable=False),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_transaction_id', name='uq_source_transaction')
    )
    op.create_index(op.f('ix_gold_contribution_contribution_date'), 'gold_contribution', ['contribution_date'], unique=False)
    op.create_index(op.f('ix_gold_contribution_contribution_type'), 'gold_contribution', ['contribution_type'], unique=False)
    op.create_index(op.f('ix_gold_contribution_contributor_id'), 'gold_contribution', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_gold_contribution_election_cycle'), 'gold_contribution', ['election_cycle'], unique=False)
    op.create_index(op.f('ix_gold_contribution_election_year'), 'gold_contribution', ['election_year'], unique=False)
    op.create_index(op.f('ix_gold_contribution_recipient_candidate_id'), 'gold_contribution', ['recipient_candidate_id'], unique=False)
    op.create_index(op.f('ix_gold_contribution_recipient_committee_id'), 'gold_contribution', ['recipient_committee_id'], unique=False)
    op.create_index(op.f('ix_gold_contribution_source_system'), 'gold_contribution', ['source_system'], unique=False)
    op.create_table('gold_contributor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('employer', sa.String(length=500), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_contributor_city'), 'gold_contributor', ['city'], unique=False)
    op.create_index(op.f('ix_gold_contributor_employer'), 'gold_contributor', ['employer'], unique=False)
    op.create_index(op.f('ix_gold_contributor_name'), 'gold_contributor', ['name'], unique=False)
    op.create_index(op.f('ix_gold_contributor_state'), 'gold_contributor', ['state'], unique=False)
    op.create_table('silver_fec_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_candidate_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('office', sa.String(length=1), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.String(length=2), nullable=True),
    sa.Column('party', sa.String(length=10), nullable=True),
    sa.Column('election_cycle', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_fec_candidate_election_cycle'), 'silver_fec_candidate', ['election_cycle'], unique=False)
    op.create_index(op.f('ix_silver_fec_candidate_source_candidate_id'), 'silver_fec_candidate', ['source_candidate_id'], unique=True)
    op.create_index(op.f('ix_silver_fec_candidate_state'), 'silver_fec_candidate', ['state'], unique=False)
    op.create_table('silver_fec_committee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_committee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('committee_type', sa.String(length=1), nullable=True),
    sa.Column('designation', sa.String(length=1), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('treasurer_name', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('election_cycle', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_fec_committee_election_cycle'), 'silver_fec_committee', ['election_cycle'], unique=False)
    op.create_index(op.f('ix_silver_fec_committee_source_committee_id'), 'silver_fec_committee', ['source_committee_id'], unique=True)
    op.create_index(op.f('ix_silver_fec_committee_state'), 'silver_fec_committee', ['state'], unique=False)
    op.create_table('silver_fec_contribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_sub_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('file_number', sa.Integer(), nullable=True),
    sa.Column('amendment_indicator', sa.String(length=10), nullable=True),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contributor_aggregate_ytd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contributor_name', sa.String(length=500), nullable=False),
    sa.Column('contributor_first_name', sa.String(length=255), nullable=True),
    sa.Column('contributor_last_name', sa.String(length=255), nullable=True),
    sa.Column('contributor_city', sa.String(length=255), nullable=True),
    sa.Column('contributor_state', sa.String(length=2), nullable=True),
    sa.Column('contributor_zip', sa.String(length=5), nullable=True),
    sa.Column('contributor_employer', sa.String(length=500), nullable=False),
    sa.Column('contributor_occupation', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('committee_id', sa.String(length=20), nullable=False),
    sa.Column('committee_name', sa.String(length=500), nullable=True),
    sa.Column('committee_type', sa.String(length=10), nullable=True),
    sa.Column('committee_designation', sa.String(length=10), nullable=True),
    sa.Column('receipt_type', sa.String(length=10), nullable=True),
    sa.Column('election_type', sa.String(length=10), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('election_cycle', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_fec_contribution_committee_id'), 'silver_fec_contribution', ['committee_id'], unique=False)
    op.create_index(op.f('ix_silver_fec_contribution_contribution_date'), 'silver_fec_contribution', ['contribution_date'], unique=False)
    op.create_index(op.f('ix_silver_fec_contribution_contributor_city'), 'silver_fec_contribution', ['contributor_city'], unique=False)
    op.create_index(op.f('ix_silver_fec_contribution_contributor_name'), 'silver_fec_contribution', ['contributor_name'], unique=False)
    op.create_index(op.f('ix_silver_fec_contribution_contributor_state'), 'silver_fec_contribution', ['contributor_state'], unique=False)
    op.create_index(op.f('ix_silver_fec_contribution_election_cycle'), 'silver_fec_contribution', ['election_cycle'], unique=False)
    op.create_index(op.f('ix_silver_fec_contribution_source_sub_id'), 'silver_fec_contribution', ['source_sub_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_fec_contribution_source_sub_id'), table_name='silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_contribution_election_cycle'), table_name='silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_contribution_contributor_state'), table_name='silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_contribution_contributor_name'), table_name='silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_contribution_contributor_city'), table_name='silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_contribution_contribution_date'), table_name='silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_contribution_committee_id'), table_name='silver_fec_contribution')
    op.drop_table('silver_fec_contribution')
    op.drop_index(op.f('ix_silver_fec_committee_state'), table_name='silver_fec_committee')
    op.drop_index(op.f('ix_silver_fec_committee_source_committee_id'), table_name='silver_fec_committee')
    op.drop_index(op.f('ix_silver_fec_committee_election_cycle'), table_name='silver_fec_committee')
    op.drop_table('silver_fec_committee')
    op.drop_index(op.f('ix_silver_fec_candidate_state'), table_name='silver_fec_candidate')
    op.drop_index(op.f('ix_silver_fec_candidate_source_candidate_id'), table_name='silver_fec_candidate')
    op.drop_index(op.f('ix_silver_fec_candidate_election_cycle'), table_name='silver_fec_candidate')
    op.drop_table('silver_fec_candidate')
    op.drop_index(op.f('ix_gold_contributor_state'), table_name='gold_contributor')
    op.drop_index(op.f('ix_gold_contributor_name'), table_name='gold_contributor')
    op.drop_index(op.f('ix_gold_contributor_employer'), table_name='gold_contributor')
    op.drop_index(op.f('ix_gold_contributor_city'), table_name='gold_contributor')
    op.drop_table('gold_contributor')
    op.drop_index(op.f('ix_gold_contribution_source_system'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_recipient_committee_id'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_recipient_candidate_id'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_election_year'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_election_cycle'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_contributor_id'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_contribution_type'), table_name='gold_contribution')
    op.drop_index(op.f('ix_gold_contribution_contribution_date'), table_name='gold_contribution')
    op.drop_table('gold_contribution')
    op.drop_index(op.f('ix_gold_committee_state'), table_name='gold_committee')
    op.drop_index(op.f('ix_gold_committee_name'), table_name='gold_committee')
    op.drop_index(op.f('ix_gold_committee_committee_type'), table_name='gold_committee')
    op.drop_index(op.f('ix_gold_committee_candidate_id'), table_name='gold_committee')
    op.drop_table('gold_committee')
    op.drop_index(op.f('ix_gold_candidate_state'), table_name='gold_candidate')
    op.drop_index(op.f('ix_gold_candidate_party'), table_name='gold_candidate')
    op.drop_index(op.f('ix_gold_candidate_office'), table_name='gold_candidate')
    op.drop_index(op.f('ix_gold_candidate_name'), table_name='gold_candidate')
    op.drop_table('gold_candidate')
    op.drop_index(op.f('ix_bronze_fec_schedule_a_source_system'), table_name='bronze_fec_schedule_a')
    op.drop_index(op.f('ix_bronze_fec_schedule_a_committee_id'), table_name='bronze_fec_schedule_a')
    op.drop_table('bronze_fec_schedule_a')
    op.drop_index(op.f('ix_bronze_fec_extraction_state_last_contribution_date'), table_name='bronze_fec_extraction_state')
    op.drop_table('bronze_fec_extraction_state')
    op.drop_index(op.f('ix_bronze_fec_committee_state'), table_name='bronze_fec_committee')
    op.drop_index(op.f('ix_bronze_fec_committee_source_system'), table_name='bronze_fec_committee')
    op.drop_table('bronze_fec_committee')
    op.drop_index(op.f('ix_bronze_fec_candidate_state'), table_name='bronze_fec_candidate')
    op.drop_index(op.f('ix_bronze_fec_candidate_source_system'), table_name='bronze_fec_candidate')
    op.drop_table('bronze_fec_candidate')
    # ### end Alembic commands ###
