"""silver/gold model refactoring

Revision ID: fd68e26103e4
Revises: d529a28e33e0
Create Date: 2025-11-20 14:04:34.963322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd68e26103e4'
down_revision: Union[str, Sequence[str], None] = 'd529a28e33e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add memo_code column to silver_fec_contribution if it doesn't exist
    # Use raw SQL with IF NOT EXISTS to handle cases where column already exists
    op.execute("""
        ALTER TABLE silver_fec_contribution
        ADD COLUMN IF NOT EXISTS memo_code VARCHAR(10)
    """)

    # Step 2a: Add source_sub_id column to gold_contribution if it doesn't exist
    op.execute("""
        ALTER TABLE gold_contribution
        ADD COLUMN IF NOT EXISTS source_sub_id VARCHAR(255)
    """)

    # Step 2b: Populate source_sub_id from source_transaction_id for existing records
    # NOTE: The old code had a bug where it used row["sub_id"] for source_transaction_id,
    # so source_transaction_id currently contains sub_id values. We copy these to source_sub_id.
    # This preserves the unique constraint but means existing data still has incorrect
    # source_transaction_id values. To get correct transaction IDs for earmark linking,
    # you should re-run the silver-to-gold transformation after this migration.
    op.execute("""
        UPDATE gold_contribution
        SET source_sub_id = source_transaction_id
        WHERE source_sub_id IS NULL
    """)

    # Step 3: Now we can safely set source_sub_id as NOT NULL
    op.alter_column('gold_contribution', 'source_sub_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # Step 4: Drop old unique constraint on (source_system, source_transaction_id)
    # Use raw SQL with IF EXISTS
    op.execute("""
        ALTER TABLE gold_contribution
        DROP CONSTRAINT IF EXISTS uq_source_transaction
    """)

    # Step 5: Create new unique constraint on (source_system, source_sub_id)
    # Check if constraint already exists before creating
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_source_sub_id'
                AND conrelid = 'gold_contribution'::regclass
            ) THEN
                ALTER TABLE gold_contribution
                ADD CONSTRAINT uq_source_sub_id UNIQUE (source_system, source_sub_id);
            END IF;
        END $$;
    """)

    # Step 6: Add index on source_transaction_id for efficient earmark pair queries
    # Use raw SQL with IF NOT EXISTS
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_gold_contribution_source_transaction_id
        ON gold_contribution (source_transaction_id)
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Drop index on source_transaction_id
    op.execute("""
        DROP INDEX IF EXISTS ix_gold_contribution_source_transaction_id
    """)

    # Step 2: Drop new unique constraint on (source_system, source_sub_id)
    op.execute("""
        ALTER TABLE gold_contribution
        DROP CONSTRAINT IF EXISTS uq_source_sub_id
    """)

    # Step 3: Recreate old unique constraint on (source_system, source_transaction_id)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_source_transaction'
                AND conrelid = 'gold_contribution'::regclass
            ) THEN
                ALTER TABLE gold_contribution
                ADD CONSTRAINT uq_source_transaction UNIQUE (source_system, source_transaction_id);
            END IF;
        END $$;
    """)

    # Step 4: Make source_sub_id nullable again
    op.alter_column('gold_contribution', 'source_sub_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # Step 5: Remove memo_code column from silver_fec_contribution if it exists
    # Use raw SQL with IF EXISTS for consistency
    op.execute("""
        ALTER TABLE silver_fec_contribution
        DROP COLUMN IF EXISTS memo_code
    """)

    # Step 6: Remove source_sub_id column from gold_contribution if it exists
    op.execute("""
        ALTER TABLE gold_contribution
        DROP COLUMN IF EXISTS source_sub_id
    """)

    # ### end Alembic commands ###
